begin;
insert into auth.users values
 ('00000000-0000-0000-0000-000000000031','test-alice@chopewash.rc4'),
 ('00000000-0000-0000-0000-000000000032','test-bob@chopewash.rc4'),
 ('00000000-0000-0000-0000-000000000033','test-charlie@chopewash.rc4');
do $$
declare
 alice uuid:='00000000-0000-0000-0000-000000000031';
 bob uuid:='00000000-0000-0000-0000-000000000032';
 charlie uuid:='00000000-0000-0000-0000-000000000033';
 snap jsonb; offer uuid; bid uuid; original_count integer; rejected boolean; booking jsonb;
begin
 perform set_config('request.jwt.claim.sub',alice::text,true);
 booking:=jsonb_build_object('kind','both','dateIso',to_char(now()+interval '1 day','YYYY-MM-DD'),'startTime','12:00','duration',45);
 snap:=rc4_action('book',booking);
 assert jsonb_array_length(snap->'bookings')=2,'paired reservation must reserve two machines';
 assert (select count(distinct pair_id) from rc4_bookings where user_id=alice)=1,'one paired reservation';
 assert (select min(starts_at) from rc4_bookings where machine_id='dryer-book')=(select min(reserved_until) from rc4_bookings where machine_id='washer-book'),'transfer buffer';
 perform set_config('request.jwt.claim.sub',bob::text,true);
 snap:=rc4_snapshot();
 assert jsonb_array_length(snap->'bookings')=0,'private bookings leaked';
 assert jsonb_array_length(snap->'intervals')=2,'shared availability missing';
 rejected:=false;
 begin perform rc4_action('book',booking||'{"kind":"wash","startTime":"12:15"}'::jsonb);
 exception when others then rejected:=true; end;
 assert rejected,'overlapping booking accepted';
 select count(*) into original_count from rc4_bookings;
 -- Washer would be free, but dryer overlaps: both inserts must roll back.
 rejected:=false;
 begin perform rc4_action('book',booking||'{"startTime":"11:00","duration":60}'::jsonb);
 exception when others then rejected:=true; end;
 assert rejected and (select count(*) from rc4_bookings)=original_count,'partial paired reservation persisted';
 rejected:=false;
 begin perform rc4_action('book',booking||'{"startTime":"15:01"}'::jsonb);
 exception when others then rejected:=true; end;
 assert rejected,'non-15-minute booking accepted';
 perform set_config('request.jwt.claim.sub',alice::text,true);
 snap:=rc4_action('joinQueue','{"kind":"washer"}');
 offer:=(snap->'queueEntries'->0->>'id')::uuid;
 assert snap->'queueEntries'->0->>'status'='offered','first resident not offered';
 perform rc4_action('joinQueue','{"kind":"washer"}');
 assert (select count(*) from rc4_queue where user_id=alice)=1,'duplicate join';
 perform set_config('request.jwt.claim.sub',bob::text,true);
 snap:=rc4_action('joinQueue','{"kind":"washer"}');
 assert (snap->'queueEntries'->0->>'position')::integer=2,'FIFO position';
 rejected:=false;
 begin perform rc4_action('claimQueue',jsonb_build_object('id',offer,'duration',30));
 exception when others then rejected:=true; end;
 assert rejected,'another user claimed offer';
 rejected:=false;
 begin perform rc4_action('operator','{"id":"dryer-book","status":"offline"}');
 exception when others then rejected:=true; end;
 assert rejected,'resident used operator controls';
 perform set_config('request.jwt.claim.sub',alice::text,true);
 snap:=rc4_action('claimQueue',jsonb_build_object('id',offer,'duration',30));
 assert (select status from rc4_machines where id='washer-queue')='running','claim did not start machine';
 rejected:=false;
 begin perform rc4_action('leaveQueue','{"kind":"washer"}');
 exception when others then rejected:=true; end;
 assert rejected,'running cycle released early';
 update rc4_queue set cycle_ends_at=now()-interval '1 second' where id=offer;
 update rc4_machines set cycle_ends_at=now()-interval '1 second' where id='washer-queue';
 perform rc4_tick();
 assert (select status from rc4_machines where id='washer-queue')='finished','finished cycle missing';
 assert (select status from rc4_queue where user_id=bob)='waiting','offered before collection';
 perform rc4_action('leaveQueue','{"kind":"washer"}');
 assert (select status from rc4_queue where user_id=bob)='offered','next user not promoted';
 perform set_config('request.jwt.claim.sub',charlie::text,true);
 perform rc4_action('joinQueue','{"kind":"washer"}');
 update rc4_queue set offer_expires_at=now()-interval '1 second' where user_id=bob;
 perform rc4_tick();
 assert (select status from rc4_queue where user_id=bob)='expired','expired turn not released';
 assert (select status from rc4_queue where user_id=charlie)='offered','FIFO after expiry';
 perform set_config('request.jwt.claim.sub',alice::text,true);
 select id into bid from rc4_bookings where user_id=alice order by starts_at limit 1;
 rejected:=false;
 begin perform rc4_action('checkIn',jsonb_build_object('id',bid));
 exception when others then rejected:=true; end;
 assert rejected,'future check-in accepted';
 perform rc4_action('cancelBooking',jsonb_build_object('id',bid));
 assert (select count(*) from rc4_bookings where user_id=alice and status='cancelled')=2,'pair cancellation';
 -- Exercise a booked cycle using database-only time adjustment in this rollback test.
 snap:=rc4_action('book',booking||'{"kind":"wash","startTime":"17:00"}'::jsonb);
 select id into bid from rc4_bookings where user_id=alice and status='confirmed';
 update rc4_bookings set starts_at=now()-interval '5 minutes',reserved_until=now()+interval '55 minutes' where id=bid;
 perform rc4_action('checkIn',jsonb_build_object('id',bid));
 assert (select status from rc4_machines where id='washer-book')='running','booked cycle did not start';
 assert (select count(*) from rc4_notifications where id=bid||':started')=1,'cycle notification missing';
 update rc4_bookings set started_at=now()-interval '46 minutes' where id=bid;
 update rc4_machines set cycle_ends_at=now()-interval '1 minute' where id='washer-book';
 perform rc4_action('collectBooking',jsonb_build_object('id',bid));
 assert (select status from rc4_machines where id='washer-book')='available','collection did not free bookable machine';
 snap:=rc4_action('book',booking||'{"kind":"dry","startTime":"18:00"}'::jsonb);
 select id into bid from rc4_bookings where user_id=alice and status='confirmed';
 update rc4_bookings set starts_at=now()-interval '16 minutes',reserved_until=now()+interval '44 minutes' where id=bid;
 perform rc4_tick();
 assert (select status from rc4_bookings where id=bid)='missed','booking grace expiry not enforced';
 perform set_config('request.jwt.claim.sub','',true);
 snap:=rc4_snapshot();
 assert jsonb_array_length(snap->'bookings')=0 and jsonb_array_length(snap->'queueEntries')=0,'anonymous private records';
 rejected:=false;
 begin perform rc4_action('joinQueue','{"kind":"dryer"}');
 exception when others then rejected:=true; end;
 assert rejected,'anonymous mutation allowed';
 assert not has_table_privilege('authenticated','rc4_bookings','INSERT'),'direct booking insert permitted';
 assert not has_table_privilege('authenticated','rc4_profiles','UPDATE'),'role escalation permitted';
 assert not has_function_privilege('authenticated','rc4_tick()','EXECUTE'),'internal scheduler exposed';
 assert not has_function_privilege('anon','rc4_action(text,jsonb)','EXECUTE'),'anonymous RPC exposed';
 raise notice 'PASS: paired atomicity, overlapping slots, privacy, FIFO, duplicate joins, offer ownership, expiry, collection and authorization';
end $$;
rollback;
